yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(
            template_name="users/logged_out.html"
        ),
        name="logout",
    ),
    path(
        "signup/",
        views.SignUp.as_view(),
        name="signup"
    ),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html"
        ),
        name="login"
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html"
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название',
        help_text='Введите название публикации',
        max_length=200
    )
    slug = models.SlugField(
        verbose_name='URL',
        help_text='Введите адрес ссылки на группу',
        max_length=25,
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Введите подробное описание группы'
    )

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'группы публикаций'
        verbose_name_plural = 'Группы публикаций'


TEXT_LENGHT: int = 15


class Post(models.Model):
    text = models.TextField(
        verbose_name='Описание',
        help_text='Введите текст публикации'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа публикации',
        help_text='Выберите группу, соотвестсвующую публикации'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'публикации'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.text[:TEXT_LENGHT]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email")

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User
from .utils import paginator_posts

FILTER_POSTS = None


def index(request):
    posts = Post.objects.all()[:FILTER_POSTS]
    page_obj = paginator_posts(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:FILTER_POSTS]
    page_obj = paginator_posts(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator_posts(request, posts)
    context = {

        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'post_change': True,
        'post_id': post_id,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


send_mail(
    'Тема письма:',
    'Текст письма:',
    'from@example.com',
    ['to@example.com'],
    fail_silently=False
)

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
<main>
{% block content %}
<div class="container col-lg-11 col-sm-12">
  <div class="row">
    <h1>Об авторе</h1>
          <div class="row">
            <div class="col-sm-6">
              <div class="author_card">
              <div class="card" style="border: none;">
                  <div class="h6 text-muted">
                    <img src="{% static 'img/author.jpeg' %}" class="author_image"
                         alt="Author image">
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="author_card">
              <div class="card" style="border: none;">
                <div class="card-body">
                  <h1>
                    Николай
                  </h1>
                  <p>
                    Всем привет! Меня зовут Николай, мне 26 лет, и я начинающий 
                    бэкенд-разработчик. Я студент 57 когорты курса 
                    <b>Python-разработчика</b>. 
                    Данное веб проложение с использованием фреймворка Django 
                    было создано с целью изучения тонкостей backend разработки.
                  </p>
                  <p>
                    <a href="https://github.com/meveladron" 
                    class="btn btn-primary">Мой профиль на GitHub</a>
                  </p>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </main>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% load static %}
{% block title %}Технологии{% endblock %}
<main>
{% block content %}
<div class="container col-lg-11 col-sm-12">
<div class="row">
  <h1>Технологии</h1>
  <div class="row row-cols-2 row-cols-md-6 g-4">
    <div class="col">
      <div class="tech_card">
        <div class="card">
        <img src="{% static 'img/tech/html.svg' %}" alt="html">
          <div class="card-body">
            <h5 class="card-title">HTML</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="tech_card">
        <div class="card">
        <img src="{% static 'img/tech/css.svg' %}" alt="html">
          <div class="card-body">
            <h5 class="card-title">CSS</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="tech_card">
        <div class="card">
        <img src="{% static 'img/tech/django.svg' %}" alt="html">
          <div class="card-body">
            <h5 class="card-title">Django</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="tech_card">
        <div class="card">
        <img src="{% static 'img/tech/python.svg' %}" alt="html">
          <div class="card-body">
            <h5 class="card-title">Python</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="tech_card">
        <div class="card">
        <img src="{% static 'img/tech/github.svg' %}" alt="html">
          <div class="card-body">
            <h5 class="card-title">Github</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="tech_card">
        <div class="card">
        <img src="{% static 'img/tech/sqlite.svg' %}" alt="html">
          <div class="card-body">
            <h5 class="card-title">SQLite</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-1 g-4">
    <p>Проект Yatube - социальная сеть для блогеров, которая предоставляет возможность
      авторам размещать свои публикации. Портал включает в себя панель администрирования,
      управление пользователями, работу с записями (создание, редактирование, удаление),
      группировку записей, пагинатор, модель отправки электронных сообщений пользователям,
      вёрстку для страниц сайта. Работа реализована при помощи фреймворка Django,
      В качестве хранения информации используется СУБД SQLite."</p>
  </div>
</div>
</div>
</div>
</main>
{% endblock %}

yatube/templates/base.html
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>
      {% block title %}
        Последние обновления на сайте
      {% endblock %}
    </title>
  </head>
  <body>
      {% include 'includes/header.html' %}
    <div class="wrapper">
      <div class="container py-5">
        <div class="custom-container">
        <div class="container col-lg-11 col-sm-12"> 
        {% block content %}
        {% endblock %}
        </div>
      </div>
      </div>
      {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<!DOCTYPE html>
<footer class="footer_bg border-top text-center py-3">
  <p class="footer_text">
    © {{ year }} Copyright <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/header.html
<!DOCTYPE html>
{% load static %}
<header>
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% endwith %}
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Пользователь: {{ request.user }}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
</header>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}

{% block header %}
  Новая публикация
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
          {% if post_change %}
            Редактировать публикацию
          {% else %}
            Новая публикация
          {% endif %}
          </div>
          <div class="card-body">
          {% if post_change %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id %}">
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create'%}">
          {% endif %}
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
                </label>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
                </small>
              {% endif %}
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                {% if post_change %}
                  Изменить
                {% else %}
                  Опубликовать
                {% endif %}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Группа {{ group.title }}{% endblock%}
{% block content %}
<h1> {{ group.title }} </h1>
<p>{{ group.description | linebreaksbr }}</p>
{% for post in page_obj %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {{ post.text | linebreaksbr }}
</p>
</article>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}
</div>

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Главная страница проекта Yatube
{% endblock %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
{% for post in page_obj %}
<article>
  <ul>
    <li>
      Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>
    {{ post.text | linebreaksbr }}
  </p>
  {% if post.group %}
<a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
  {% endif %}
</article>
  {% if not forloop.last %}
<hr>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Запись {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load user_filters %}
  <h1>
    Публикация автора: {{ post.author.get_full_name }}
  </h1>
  <br>
  <article>
  <li>
    Автор: {{ post.author.get_full_name }}
    <a href="{% url 'posts:profile' post.author.username %}"></a>
  </li>
  <li>
    Дата публикации:
    {{ post.pub_date|date:"d E Y" }}
  </li>
  {% if post.group %}
  <li>
    Группа:
    <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
  </li>
  {% endif %}
  </ul>
  <p>
    {{ post.text|linebreaks }}
  </p>
  {% if user == post.author %}
  <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
    редактировать запись
  </a>
{% endif %}
</article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профиль пользователя {{ user.get_full_name }}{% endblock %}
{% block content %}
{% load user_filters %}
  <h1>
    Все записи автора {{ author.get_full_name }}
  </h1>
  <h5>
    Количество записей: {{ author.posts.count }}
  </h5>
  <br>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ user.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li>
          Группа:
          <a href="{% url 'posts:group_list' post.group.slug %}">
          {{ post.group.title }}</a>
        </li>
        {% endif %}
      </ul>
      <p>
        {{ post.text|linebreaks }}
        <a href="{% url 'posts:post_detail' post.pk %}">(Подробная информация)</a>
      </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
<main>
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
</div>
</main>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
<main>
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Войти на сайт
      </div>
      <div class="card-body">
        {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
        {% endif %}

        <form method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}>
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group row my-3"
            {% if field.field.required %}
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}>
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            <div>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</main>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
<main>
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body">
            <p>Пароль изменён успешно</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}

{% block title %}Изменение пароля{% endblock %}

{% block content %}
{% load user_filters %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_change' %}">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}
  Сброс пароля
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:password_reset' %}">
              <input type="hidden" name="csrfmiddlewaretoken" value="">
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
  Зарегистрироваться
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %} 
                  {% for error in field.errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}